filter {
  check-by=NAME
  record-mode=BLACKLIST
  blacklist=[]
  whitelist=[]
}
path="replay/player/${name}@${uuid}"
instant-replay {
  enable=false
  length=5
  interval=1
  path="replay/instant/${name}@${uuid}"
}
record-suspicious {
  themis=false
  matrix=true
  vulcan=false
  negativity=false
  grim=false
  light-anti-cheat=false
  spartan=false
  length=5
  path="replay/suspicious/${name}@${uuid}"
}
clear-outdated-record {
  enable=true
  interval=24
  days=7
}
pause-recording-on-high-speed {
  enable=false
  threshold=30.0
}
delete-tmp-file-on-load=false
photographer-prefix=""
